// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbixismyhxipqobwgcle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiaXhpc215aHhpcHFvYndnY2xlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3Nzc4NDYsImV4cCI6MjA2MTM1Mzg0Nn0.h1p3LLDCcKBa-qJR5VYYkjq2ff6UExRQRj3LG50YD64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);